name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  js:
    name: modal-js check and build
    timeout-minutes: 5
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: true

      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: "22"

      - run: npm ci
        working-directory: ./modal-js

      - run: npm run format:check
        working-directory: ./modal-js

      - run: npm run check
        working-directory: ./modal-js

      - run: npm run build
        working-directory: ./modal-js
